<?php
/**
 * Copyright (c) 2020, Nosto Solutions Ltd
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Nosto Solutions Ltd <contact@nosto.com>
 * @copyright 2020 Nosto Solutions Ltd
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 *
 */

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Nosto\Tagging\Block\Addtocart;

/**
 * @var Addtocart $block
 * @var SecureHtmlRenderer $secureRenderer
 */
$isHyva = $block->isHyva();
?>

  <form <?= $isHyva ? 'x-data="nostoRecobuy()"' : '' ?>
    action="<?= $block->escapeUrl($block->getSubmitUrl()) ?>"
    method="post" id="nosto_addtocart_form">
      <?= $block->getBlockHtml('formkey') ?>
  </form>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['src' => $block->escapeUrl($block->getViewFileUrl('Nosto_Tagging::js/recobuy-core.js'))], '', false) ?>

<?php if ($isHyva): ?>
  <!-- Hyva Theme with Alpine.js -->
    <?php
    $script = <<<script
      function nostoRecobuy() {
          'use strict';

          window.RecobuyCore.reloadCart = function () {
              window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
          };

          window.Nosto = window.Nosto || {};
          Object.assign(window.Nosto, window.RecobuyCore);

          return window.RecobuyCore;
      }
  script;
    ?>
<?php else: ?>
  <!-- Luma with RequireJS -->
    <?php
    $script = <<<script
      window.RecobuyCore.reloadCart = function () {
          require(['Magento_Customer/js/customer-data'], function (customerData) {
              customerData.reload(['cart', 'messages'], true);
          });
      };

      window.Nosto = window.RecobuyCore;
  script;
    ?>
<?php endif; ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false) ?>
