<?php
/**
 * Copyright (c) 2019, Nosto Solutions Ltd
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Nosto Solutions Ltd <contact@nosto.com>
 * @copyright 2019 Nosto Solutions Ltd
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 *
 */

/**
 * Template for cart tagging. The actual data is populated via
 * Magento's KnockoutJS logic.
 *
 * @see \Nosto\Tagging\CustomerData\CartTagging
 */
?>
<!-- Nosto Cart Tagging -->
<div class="nosto_cart_hidden" style="display:none" data-bind="scope: 'cartTagging'"
     data-role="nosto-cart-tagging"
     id="nosto_cart_tagging">
    <span class="hcid" data-bind="text: cartTagging().hcid"></span>
    <span class="restore_link" data-bind="text: cartTagging().restore_cart_url"></span>
    <!-- ko if: cartTagging().itemCount > 0 -->
    <!-- ko foreach: {data: cartTagging().items, afterRender: sendTagging } -->
    <div class="line_item">
        <span class="product_id" data-bind="text: $data.product_id"></span>
        <span class="sku_id" data-bind="text: $data.sku_id"></span>
        <span class="quantity" data-bind="text: $data.quantity"></span>
        <span class="name" data-bind="text: $data.name"></span>
        <span class="unit_price" data-bind="text: $data.unit_price"></span>
        <span class="price_currency_code" data-bind="text: $data.price_currency_code"></span>
    </div>
    <!-- /ko -->
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{"[data-role=nosto-cart-tagging]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>