<?php
/**
 * Copyright (c) 2019, Nosto Solutions Ltd
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Nosto Solutions Ltd <contact@nosto.com>
 * @copyright 2019 Nosto Solutions Ltd
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 *
 */

/**
 *     ______     ___     ____  _____  ___   _________   ________ ______  _____ _________
 *    |_   _ `. .'   `.  |_   \|_   _.'   `.|  _   _  | |_   __  |_   _ `|_   _|  _   _  |
 *      | | `. /  .-.  \   |   \ | |/  .-.  |_/ | | \_|   | |_ \_| | | `. \| | |_/ | | \_|
 *      | |  | | |   | |   | |\ \| || |   | |   | |       |  _| _  | |  | || |     | |
 *     _| |_.' \  `-'  /  _| |_\   |\  `-'  /  _| |_     _| |__/ |_| |_.' _| |_   _| |_
 *    |______.' `.___.'  |_____|\____`.___.'  |_____|   |________|______.|_____| |_____|
 *
 * Nosto sends information over both the API and the broswer tagging. Values for the tagging is generated
 * via the Nosto corresponding objects. In order to customize the values in the markup below, you will need
 * to override the core parts of the extension. Failure to do so will result in broken and incorrect
 * recommendations.
 * Please see a reference guide such as https://github.com/Nosto/nosto-magento2/wiki
 */

/**
 * Template for customer tagging. The actual data is populated via
 * Magento's KnockoutJS logic.
 *
 * @see \Nosto\Tagging\CustomerData\CustomerTagging
 */
?>
<!-- Nosto Customer Tagging -->
<div id="nosto_customer_tagging" class="nosto_customer_hidden" style="display:none"
     data-bind="scope: 'customerTagging'"
     data-role="nosto-customer-tagging">
    <!-- ko if: customerTagging().first_name -->
    <!-- ko foreach: {data: customerTagging(), afterRender: sendTagging } -->
    <span class="first_name" data-bind="text: $data.first_name"></span>
    <span class="last_name" data-bind="text: $data.last_name"></span>
    <span class="email" data-bind="text: $data.email"></span>
    <span class="hcid" data-bind="text: $data.hcid"></span>
    <span class="customer_reference" data-bind="text: $data.customer_reference"></span>
    <span class="marketing_permission" data-bind="text: $data.marketing_permission"></span>
    <span class="date_of_birth" data-bind="text: $data.date_of_birth"></span>
    <span class="customer_group" data-bind="text: $data.customer_group"></span>
    <span class="gender" data-bind="text: $data.gender"></span>
    <!-- /ko -->
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{"[data-role=nosto-customer-tagging]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>