<?php
/* @var Nosto\Tagging\Block\MonitoringLogin $block */
?>
<div class="row">
    <div class="col-md-8">
        <form name="login" method="post" id="login" class="form"
              action="<?php echo $block->getLoginFormAction('nosto/monitoring/submit') ?>'); ?>"
              data-hasrequired="<?= __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}'>
            <div class="fields col-md-6">
                <div class="field token required">
                    <label class="label" for="token"><span><?= __('Token') ?></span></label>
                    <div class="control">
                        <input name="token" id="token" title="Token" value="" class="input-text" type="text"
                               data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                    </div>
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Login"><span><?= __('Login') ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>