<?php
/* @var Nosto\Tagging\Block\MonitoringIndexer $block */
?>
<a href="<?php echo $block->getFormAction('nosto/monitoring/') ?>">Go back</a>
<?php
/* @var Nosto\Tagging\Block\MonitoringIndexer $block */
if ('product' === $block->getEntityType()) {
    dump($block->getNostoProduct());
}
if ('order' === $block->getEntityType()) {
    dump($block->getNostoOrder());
}
if ('category' === $block->getEntityType()) {
    dump($block->getNostoCategory());
}
?>
<div class="row">
    <div class="col-md-8">
        <form name="sync" method="post" id="sync" class="form"
              action="<?php echo $block->getFormAction('nosto/monitoring/sync') ?>"
              data-mage-init='{"validation":{}}'>
            <input name="entity_id" id="entity_id" title="Entity ID" value="<?= $block->getEntityId() ?>"
                   class="input-text" type="hidden"
                   data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
            <input name="entity_type" id="entity_type" title="Entity type" value="<?= $block->getEntityType() ?>"
                   class="input-text" type="hidden"
                   data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Sync">Sync</span></button>
                </div>
            </div>
        </form>
    </div>
</div>
