<?php
/** @var \Nosto\Tagging\Block\Order $this */

$order = $this->getNostoOrder();
?>

<?php if ($order->getItems() !== array()) : ?>
    <!-- Nosto Order Tagging -->
    <div class="nosto_purchase_order" style="display:none">
        <span class="order_number"><?php echo $order->getOrderNumber(); ?></span>
        <span class="external_order_ref"><?php echo $this->escapeHtml($order->getExternalRef()); ?></span>
        <?php if ($order->getStatus()) : ?>
            <span class="order_status_code"><?php echo $this->escapeHtml($order->getStatus()->getCode()); ?></span>
            <span class="order_status_label"><?php echo $this->escapeHtml($order->getStatus()->getLabel()); ?></span>
        <?php endif; ?>
        <span class="payment_provider"><?php echo $this->escapeHtml($order->getPaymentProvider()->getProvider()); ?></span>
        <div class="buyer">
            <?php if ($order->getBuyer()) : ?>
                <?php if ($order->getBuyer()->getFirstName()) : ?>
                    <span class="first_name"><?php echo $this->escapeHtml($order->getBuyer()->getFirstName()); ?></span>
                <?php endif; ?>
                <?php if ($order->getBuyer()->getLastName()) : ?>
                    <span class="last_name"><?php echo $this->escapeHtml($order->getBuyer()->getLastName()); ?></span>
                <?php endif; ?>
                <?php if ($order->getBuyer()->getEmail()) : ?>
                    <span class="email"><?php echo $this->escapeHtml($order->getBuyer()->getEmail()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="purchased_items">
            <?php foreach ($order->getItems() as $item) : ?>
                <div class="line_item">
                    <span class="product_id"><?php echo (int)$item->getItemId(); ?></span>
                    <span class="quantity"><?php echo (int)$item->getQuantity(); ?></span>
                    <span class="name"><?php echo $this->escapeHtml($item->getName()); ?></span>
                    <span class="unit_price"><?php echo $this->formatNostoPrice($item->getUnitPrice()); ?></span>
                    <span class="price_currency_code"><?php echo strtoupper($item->getCurrency()->getCode()); ?></span>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>