<?php
/**
 * Copyright (c) 2017, Nosto Solutions Ltd
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Nosto Solutions Ltd <contact@nosto.com>
 * @copyright 2017 Nosto Solutions Ltd
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 *
 */

/** @var \Nosto\Tagging\Block\Order $this */

$order = $this->getNostoOrder();
?>

<?php if ($order->getPurchasedItems() !== array()) : ?>
    <!-- Nosto Order Tagging -->
    <div class="nosto_purchase_order" style="display:none">
        <span class="order_number"><?php echo $order->getOrderNumber(); ?></span>
        <span
                class="external_order_ref"><?php echo $this->escapeHtml($order->getExternalOrderRef()); ?></span>
        <?php if ($order->getOrderStatusCode()) : ?>
            <span
                    class="order_status_code"><?php echo $this->escapeHtml($order->getOrderStatusCode()); ?></span>
        <?php endif; ?>
        <?php if ($order->getOrderStatusLabel()) : ?>
            <span
                    class="order_status_label"><?php echo $this->escapeHtml($order->getOrderStatusLabel()); ?></span>
        <?php endif; ?>
        <span
                class="payment_provider"><?php echo $this->escapeHtml($order->getPaymentProvider()); ?></span>
        <div class="buyer">
            <?php if ($order->getCustomer()) : ?>
                <?php if ($order->getCustomer()->getFirstName()) : ?>
                    <span
                            class="first_name"><?php echo $this->escapeHtml($order->getCustomer()->getFirstName()); ?></span>
                <?php endif; ?>
                <?php if ($order->getCustomer()->getLastName()) : ?>
                    <span
                            class="last_name"><?php echo $this->escapeHtml($order->getCustomer()->getLastName()); ?></span>
                <?php endif; ?>
                <?php if ($order->getCustomer()->getEmail()) : ?>
                    <span
                            class="email"><?php echo $this->escapeHtml($order->getCustomer()->getEmail()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="purchased_items">
            <?php foreach ($order->getPurchasedItems() as $item) : ?>
                <div class="line_item">
                    <span class="product_id"><?php echo (int)$item->getProductId(); ?></span>
                    <span class="quantity"><?php echo (int)$item->getQuantity(); ?></span>
                    <span class="name"><?php echo $this->escapeHtml($item->getName()); ?></span>
                    <span class="unit_price"><?php echo $this->formatNostoPrice($item->getUnitPrice()); ?></span>
                    <span
                            class="price_currency_code"><?php echo strtoupper($item->getPriceCurrencyCode()); ?></span>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>