<?php
/**
 * Copyright (c) 2017, Nosto Solutions Ltd
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Nosto Solutions Ltd <contact@nosto.com>
 * @copyright 2017 Nosto Solutions Ltd
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 *
 */

/** @var \Nosto\Tagging\Block\Product $this */

$product = $this->getNostoProduct();
$category = $this->getNostoCategory();
?>

    <!-- Nosto Product Tagging -->
    <div class="nosto_product" style="display:none">
        <span class="url"><?php echo $this->escapeUrl($product->getUrl()); ?></span>
        <span class="product_id"><?php echo $this->escapeHtml($product->getProductId()); ?></span>
        <span class="name"><?php echo $this->escapeHtml($product->getName()); ?></span>
        <span class="image_url"><?php echo $this->escapeUrl($product->getImageUrl()); ?></span>
        <span class="price"><?php echo $this->formatNostoPrice($product->getPrice()); ?></span>
        <span class="price_currency_code"><?php echo $product->getPriceCurrencyCode(); ?></span>
        <span class="availability"><?php echo $product->getAvailability(); ?></span>
        <?php foreach ($product->getCategories() as $cat) : ?>
            <span class="category"><?php echo $this->escapeHtml($cat); ?></span>
        <?php endforeach; ?>
        <?php if ($product->getDescription()) : ?>
            <span
                class="description"><?php echo $this->escapeHtml($this->stripTags($product->getDescription())); ?></span>
        <?php endif; ?>
        <?php if ($product->getListPrice()) : ?>
            <span
                class="list_price"><?php echo $this->formatNostoPrice($product->getListPrice()); ?></span>
        <?php endif; ?>
        <?php if ($product->getBrand()) : ?>
            <span class="brand"><?php echo $this->escapeHtml($product->getBrand()); ?></span>
        <?php endif; ?>
        <?php foreach ($product->getTag1() as $tag) : ?>
            <span class="tag1"><?php echo $this->escapeHtml($tag); ?></span>
        <?php endforeach; ?>
        <?php foreach ($product->getTag2() as $tag) : ?>
            <span class="tag2"><?php echo $this->escapeHtml($tag); ?></span>
        <?php endforeach; ?>
        <?php foreach ($product->getTag3() as $tag) : ?>
            <span class="tag3"><?php echo $this->escapeHtml($tag); ?></span>
        <?php endforeach; ?>
        <?php if ($product->getGtin()) : ?>
            <span class="gtin"><?php echo $this->escapeHtml($product->getGtin()); ?></span>
        <?php endif; ?>
    </div>
<?php if ($category) : ?>
    <div class="nosto_category"
         style="display:none"><?php echo $this->escapeHtml($category); ?></div>
<?php endif; ?>