<?php
/** @var \Nosto\Tagging\Block\Product $this */

$product = $this->getNostoProduct();
$category = $this->getNostoCategory();
?>

<!-- Nosto Product Tagging -->
<div class="nosto_product" style="display:none">
    <span class="url"><?php echo $this->escapeUrl($product->getUrl()); ?></span>
    <span class="product_id"><?php echo $this->escapeHtml($product->getProductId()); ?></span>
    <span class="name"><?php echo $this->escapeHtml($product->getName()); ?></span>
    <span class="image_url"><?php echo $this->escapeUrl($product->getImageUrl()); ?></span>
    <?php if ($product->getPrice()): ?>
        <span class="price"><?php echo $this->formatNostoPrice($product->getPrice()); ?></span>
    <?php endif; ?>
    <?php if ($product->getCurrency()): ?>
        <span class="price_currency_code"><?php echo $this->escapeHtml($product->getCurrency()->getCode()); ?></span>
    <?php endif; ?>
    <?php if ($product->getAvailability()): ?>
        <span class="availability"><?php echo $this->escapeHtml($product->getAvailability()->getAvailability()); ?></span>
    <?php endif; ?>
    <?php foreach ($product->getCategories() as $cat): ?>
        <span class="category"><?php echo $this->escapeHtml($cat->getPath()); ?></span>
    <?php endforeach; ?>
    <?php if ($product->getFullDescription()): ?>
        <span class="description"><?php echo $this->escapeHtml($product->getFullDescription()); ?></span>
    <?php endif; ?>
    <?php if ($product->getListPrice()): ?>
        <span class="list_price"><?php echo $this->formatNostoPrice($product->getListPrice()); ?></span>
    <?php endif; ?>
    <?php if ($product->getBrand()): ?>
        <span class="brand"><?php echo $this->escapeHtml($product->getBrand()); ?></span>
    <?php endif; ?>
    <?php foreach ($product->getTags() as $type => $tags): ?>
        <?php foreach ($tags as $tag): ?>
            <span class="<?php echo $this->escapeQuote($type); ?>"><?php echo $this->escapeHtml($tag); ?></span>
        <?php endforeach; ?>
    <?php endforeach; ?>
    <?php if ($product->getDatePublished()): ?>
        <span class="date_published"><?php echo $this->formatNostoDate($product->getDatePublished()); ?></span>
    <?php endif; ?>
    <?php if ($this->getStoreHasMultiCurrency()): ?>
        <span class="variation_id"><?php echo $this->escapeHtml($product->getPriceVariationId()); ?></span>
        <?php if ($this->inclPriceVariations() && count($product->getPriceVariations()) > 0): ?>
            <?php foreach ($product->getPriceVariations() as $variation): ?>
                <div class="variation">
                    <span class="variation_id"><?php echo $this->escapeHtml($variation->getId()->getId()); ?></span>
                    <span class="price_currency_code"><?php echo $this->escapeHtml($variation->getCurrency()->getCode()); ?></span>
                    <span class="price"><?php echo $this->formatNostoPrice($variation->getPrice()); ?></span>
                    <span class="list_price"><?php echo $this->formatNostoPrice($variation->getListPrice()); ?></span>
                    <span class="availability"><?php echo $this->escapeHtml($variation->getAvailability()->getAvailability()); ?></span>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>
<?php if ($category): ?>
    <div class="nosto_category" style="display:none"><?php echo $this->escapeHtml($category->getPath()); ?></div>
<?php endif; ?>