<?php
/**
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$script = <<<script
    window.addEventListener('load', (event) => {
      //noinspection AmdModulesDependencies,JSUnresolvedVariable
      if (typeof nostojs === 'function') {
          // noinspection JSUnresolvedVariable
          return nostojs;
      } else if (typeof window['nostojs'] === 'function') {
        return window['nostojs'];
      }
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false) ?>
