<?php
/**
 * @var $this NNosto\Tagging\Block\Adminhtml\Form\Field\SSOToken
 */
?>

<style>
    .token-container{
        background: #f3f4f4;
    }
    .token-title{
        color: #303030;
        float: none;
        font-size: 14px;
        font-weight: 600;
        padding-right: 30px;
        text-align: right;
        width: 33%;
        text-transform: capitalize;
    }
</style>
<fieldset>
    <table>
        <tr>
            <td class="token-title">
                Account ID
            </td>
            <td class="token-container">
                <?php echo $this->getAccountDetails()->getName() ?>
            </td>
        </tr>

        <?php foreach ($this->getAccountDetails()->getTokens() as $token) {
            echo '<tr>
            <td class="token-title">
                '. $token->getName().' Token
            </td>
            <td class="token-container">
                '. $token->getValue().'
            </td>
        </tr>';
        }
        ?>
    </table>

<!--    <div>-->
<!--        <ul>-->
<!--            <li>-->
<!--                SSO TOKEN: TOKEN-->
<!--            </li>-->
<!--        </ul>-->
<!--    </div>-->
</fieldset>
