<?php
/**
 * @var $this NNosto\Tagging\Block\Adminhtml\Form\Field\SSOToken
 */
?>

<style>
    .token-container{
        background: #f3f4f4;
    }
    .token-title{
        color: #303030;
        float: none;
        font-size: 14px;
        font-weight: 600;
        padding-right: 30px;
        text-align: right;
        width: 33%;
        text-transform: capitalize;
    }
</style>
<fieldset>
    <?php if($this->getAccountDetails() == null) : ?>
        <div>
            <?php echo new \Magento\Framework\Phrase('There is no account connected') ?>
        </div>
    <?php else: ?>
        <table>
            <tr>
                <td class="token-title">
                    Account ID
                </td>
                <td class="token-container">
                    <?php echo $this->getAccountDetails()->getName(); ?>
                </td>
            </tr>

        <?php foreach($this->getAccountDetails()->getTokens() as $token): ?>
            <tr>
                <td class="token-title">
                    <?php echo $token->getName() ?> Token
                </td>
                <td class="token-container">
                    <?php echo $token->getValue() ?>
                </td>
            </tr>
        <?php endforeach; ?>

        </table>
    <?php endif; ?>

</fieldset>